[package]
name = "host"
version = "0.1.0"
edition = "2021"


[dependencies]
risc0-zkvm  = "0.11.1"               
sha3        = "0.10"
anyhow      = "1"
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
hex         = "0.4"

