[package]
name = "dilithium-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
crystals-dilithium = "1.0.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
hex = "0.4"
rand = "0.8"