[package]
name = "dilithium_verifier"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "2.3", default-features = false, features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10", default-features = false }