[profile.default]
# --- folders ---
src  = "src"
out  = "out"
libs = ["lib"]

# --- compiler ---
solc_version     = "0.8.20"   # explicit compiler tag
optimizer        = true
optimizer_runs   = 200

# --- optional: enable off-chain helpers later ---
# Allow Forge tests to call Node scripts (vm.ffi) when we integrate qsafe-signer:
ffi = true
# Let tests read files (e.g. pre-generated Dilithium sig hex files) in this repo:
fs_permissions = [{ access = "read", path = "./" }]
