[package]
name = "tools-encode-input"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "encode_input"
path = "encode_input.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
risc0-zkvm = "1.0"